Created a simple list of different tools and templates of Neutralinoj…
neutralinojs/neutralinojs.github.io pull request #288
Opened 2023-11-15 14:17 UTC by devanshkansagra

…s #239

2023-12-02 14:16 UTC, devanshkansagra commented
Please check the pull request.

2023-12-22 14:56 UTC, devanshkansagra commented
The list like this I 've created please check. [](https://github.com/neutralinojs/neutralinojs.github.io/assets/125076549/305b8b8d-7cf9-470e-a521-01a52e788bcc
)

2023-12-22 14:56 UTC, devanshkansagra commented
I have created list like this
https://github.com/neutralinojs/neutralinojs.github.io/assets/125076549/305b8b8d-7cf9-470e-a521-01a52e788bcc

2024-01-11 06:53 UTC, shalithasuranga commented on src/pages/styles.module.css
> +}
Thanks for sending this pull requestion. A small comment regarding CSS. Could you please avoid adding custom CSS and use existing Docusaurus CSS class names? You can find more about styling from [this link](https://docusaurus.io/docs/styling-layout) and [Infima website](https://infima.dev/). Once you've done these updates, we can merge this pull request. Please let me know if you have questions. Thanks :tada:

2024-01-11 06:54 UTC, shalithasuranga requested changes
Please check the inline comment...

2024-01-11 07:53 UTC, devanshkansagra commented on src/pages/styles.module.css
> +}
Sure No Problem

2024-01-11 07:59 UTC, devanshkansagra commented
Hey Can I create a new Branch coz my old directory was deleted due to system failure

2024-01-11 12:26 UTC, shalithasuranga commented
Hello @devanshkansagra , Sure, no problem :)

2024-01-11 13:02 UTC, closed without merging